/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as ConsultarRouteImport } from './routes/consultar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentoUploadRouteImport } from './routes/documento.upload'
import { Route as DocumentoUnidadeRouteImport } from './routes/documento.unidade'
import { Route as DocumentoSucessoRouteImport } from './routes/documento.sucesso'
import { Route as DocumentoRevisaoRouteImport } from './routes/documento.revisao'
import { Route as DocumentoIplRouteImport } from './routes/documento.ipl'
import { Route as DocumentoAdvogadoRouteImport } from './routes/documento.advogado'
import { Route as AgendarUnidadeRouteImport } from './routes/agendar.unidade'
import { Route as AgendarSucessoRouteImport } from './routes/agendar.sucesso'
import { Route as AgendarRevisaoRouteImport } from './routes/agendar.revisao'
import { Route as AgendarRegrasRouteImport } from './routes/agendar.regras'
import { Route as AgendarIplRouteImport } from './routes/agendar.ipl'
import { Route as AgendarHorarioRouteImport } from './routes/agendar.horario'
import { Route as AgendarDataRouteImport } from './routes/agendar.data'
import { Route as AgendarAdvogadoRouteImport } from './routes/agendar.advogado'
import { Route as AdminConviteRouteImport } from './routes/admin.convite'

const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarRoute = ConsultarRouteImport.update({
  id: '/consultar',
  path: '/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoUploadRoute = DocumentoUploadRouteImport.update({
  id: '/documento/upload',
  path: '/documento/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoUnidadeRoute = DocumentoUnidadeRouteImport.update({
  id: '/documento/unidade',
  path: '/documento/unidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoSucessoRoute = DocumentoSucessoRouteImport.update({
  id: '/documento/sucesso',
  path: '/documento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoRevisaoRoute = DocumentoRevisaoRouteImport.update({
  id: '/documento/revisao',
  path: '/documento/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoIplRoute = DocumentoIplRouteImport.update({
  id: '/documento/ipl',
  path: '/documento/ipl',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoAdvogadoRoute = DocumentoAdvogadoRouteImport.update({
  id: '/documento/advogado',
  path: '/documento/advogado',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarUnidadeRoute = AgendarUnidadeRouteImport.update({
  id: '/agendar/unidade',
  path: '/agendar/unidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSucessoRoute = AgendarSucessoRouteImport.update({
  id: '/agendar/sucesso',
  path: '/agendar/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRevisaoRoute = AgendarRevisaoRouteImport.update({
  id: '/agendar/revisao',
  path: '/agendar/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRegrasRoute = AgendarRegrasRouteImport.update({
  id: '/agendar/regras',
  path: '/agendar/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarIplRoute = AgendarIplRouteImport.update({
  id: '/agendar/ipl',
  path: '/agendar/ipl',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarHorarioRoute = AgendarHorarioRouteImport.update({
  id: '/agendar/horario',
  path: '/agendar/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarDataRoute = AgendarDataRouteImport.update({
  id: '/agendar/data',
  path: '/agendar/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarAdvogadoRoute = AgendarAdvogadoRouteImport.update({
  id: '/agendar/advogado',
  path: '/agendar/advogado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConviteRoute = AdminConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultar': typeof ConsultarRoute
  '/gestao': typeof GestaoRoute
  '/admin/convite': typeof AdminConviteRoute
  '/agendar/advogado': typeof AgendarAdvogadoRoute
  '/agendar/data': typeof AgendarDataRoute
  '/agendar/horario': typeof AgendarHorarioRoute
  '/agendar/ipl': typeof AgendarIplRoute
  '/agendar/regras': typeof AgendarRegrasRoute
  '/agendar/revisao': typeof AgendarRevisaoRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/agendar/unidade': typeof AgendarUnidadeRoute
  '/documento/advogado': typeof DocumentoAdvogadoRoute
  '/documento/ipl': typeof DocumentoIplRoute
  '/documento/revisao': typeof DocumentoRevisaoRoute
  '/documento/sucesso': typeof DocumentoSucessoRoute
  '/documento/unidade': typeof DocumentoUnidadeRoute
  '/documento/upload': typeof DocumentoUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultar': typeof ConsultarRoute
  '/gestao': typeof GestaoRoute
  '/admin/convite': typeof AdminConviteRoute
  '/agendar/advogado': typeof AgendarAdvogadoRoute
  '/agendar/data': typeof AgendarDataRoute
  '/agendar/horario': typeof AgendarHorarioRoute
  '/agendar/ipl': typeof AgendarIplRoute
  '/agendar/regras': typeof AgendarRegrasRoute
  '/agendar/revisao': typeof AgendarRevisaoRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/agendar/unidade': typeof AgendarUnidadeRoute
  '/documento/advogado': typeof DocumentoAdvogadoRoute
  '/documento/ipl': typeof DocumentoIplRoute
  '/documento/revisao': typeof DocumentoRevisaoRoute
  '/documento/sucesso': typeof DocumentoSucessoRoute
  '/documento/unidade': typeof DocumentoUnidadeRoute
  '/documento/upload': typeof DocumentoUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultar': typeof ConsultarRoute
  '/gestao': typeof GestaoRoute
  '/admin/convite': typeof AdminConviteRoute
  '/agendar/advogado': typeof AgendarAdvogadoRoute
  '/agendar/data': typeof AgendarDataRoute
  '/agendar/horario': typeof AgendarHorarioRoute
  '/agendar/ipl': typeof AgendarIplRoute
  '/agendar/regras': typeof AgendarRegrasRoute
  '/agendar/revisao': typeof AgendarRevisaoRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/agendar/unidade': typeof AgendarUnidadeRoute
  '/documento/advogado': typeof DocumentoAdvogadoRoute
  '/documento/ipl': typeof DocumentoIplRoute
  '/documento/revisao': typeof DocumentoRevisaoRoute
  '/documento/sucesso': typeof DocumentoSucessoRoute
  '/documento/unidade': typeof DocumentoUnidadeRoute
  '/documento/upload': typeof DocumentoUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consultar'
    | '/gestao'
    | '/admin/convite'
    | '/agendar/advogado'
    | '/agendar/data'
    | '/agendar/horario'
    | '/agendar/ipl'
    | '/agendar/regras'
    | '/agendar/revisao'
    | '/agendar/sucesso'
    | '/agendar/unidade'
    | '/documento/advogado'
    | '/documento/ipl'
    | '/documento/revisao'
    | '/documento/sucesso'
    | '/documento/unidade'
    | '/documento/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consultar'
    | '/gestao'
    | '/admin/convite'
    | '/agendar/advogado'
    | '/agendar/data'
    | '/agendar/horario'
    | '/agendar/ipl'
    | '/agendar/regras'
    | '/agendar/revisao'
    | '/agendar/sucesso'
    | '/agendar/unidade'
    | '/documento/advogado'
    | '/documento/ipl'
    | '/documento/revisao'
    | '/documento/sucesso'
    | '/documento/unidade'
    | '/documento/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consultar'
    | '/gestao'
    | '/admin/convite'
    | '/agendar/advogado'
    | '/agendar/data'
    | '/agendar/horario'
    | '/agendar/ipl'
    | '/agendar/regras'
    | '/agendar/revisao'
    | '/agendar/sucesso'
    | '/agendar/unidade'
    | '/documento/advogado'
    | '/documento/ipl'
    | '/documento/revisao'
    | '/documento/sucesso'
    | '/documento/unidade'
    | '/documento/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultarRoute: typeof ConsultarRoute
  GestaoRoute: typeof GestaoRoute
  AgendarAdvogadoRoute: typeof AgendarAdvogadoRoute
  AgendarDataRoute: typeof AgendarDataRoute
  AgendarHorarioRoute: typeof AgendarHorarioRoute
  AgendarIplRoute: typeof AgendarIplRoute
  AgendarRegrasRoute: typeof AgendarRegrasRoute
  AgendarRevisaoRoute: typeof AgendarRevisaoRoute
  AgendarSucessoRoute: typeof AgendarSucessoRoute
  AgendarUnidadeRoute: typeof AgendarUnidadeRoute
  DocumentoAdvogadoRoute: typeof DocumentoAdvogadoRoute
  DocumentoIplRoute: typeof DocumentoIplRoute
  DocumentoRevisaoRoute: typeof DocumentoRevisaoRoute
  DocumentoSucessoRoute: typeof DocumentoSucessoRoute
  DocumentoUnidadeRoute: typeof DocumentoUnidadeRoute
  DocumentoUploadRoute: typeof DocumentoUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar': {
      id: '/consultar'
      path: '/consultar'
      fullPath: '/consultar'
      preLoaderRoute: typeof ConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/upload': {
      id: '/documento/upload'
      path: '/documento/upload'
      fullPath: '/documento/upload'
      preLoaderRoute: typeof DocumentoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/unidade': {
      id: '/documento/unidade'
      path: '/documento/unidade'
      fullPath: '/documento/unidade'
      preLoaderRoute: typeof DocumentoUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/sucesso': {
      id: '/documento/sucesso'
      path: '/documento/sucesso'
      fullPath: '/documento/sucesso'
      preLoaderRoute: typeof DocumentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/revisao': {
      id: '/documento/revisao'
      path: '/documento/revisao'
      fullPath: '/documento/revisao'
      preLoaderRoute: typeof DocumentoRevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/ipl': {
      id: '/documento/ipl'
      path: '/documento/ipl'
      fullPath: '/documento/ipl'
      preLoaderRoute: typeof DocumentoIplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/advogado': {
      id: '/documento/advogado'
      path: '/documento/advogado'
      fullPath: '/documento/advogado'
      preLoaderRoute: typeof DocumentoAdvogadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/unidade': {
      id: '/agendar/unidade'
      path: '/agendar/unidade'
      fullPath: '/agendar/unidade'
      preLoaderRoute: typeof AgendarUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/sucesso': {
      id: '/agendar/sucesso'
      path: '/agendar/sucesso'
      fullPath: '/agendar/sucesso'
      preLoaderRoute: typeof AgendarSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/revisao': {
      id: '/agendar/revisao'
      path: '/agendar/revisao'
      fullPath: '/agendar/revisao'
      preLoaderRoute: typeof AgendarRevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/regras': {
      id: '/agendar/regras'
      path: '/agendar/regras'
      fullPath: '/agendar/regras'
      preLoaderRoute: typeof AgendarRegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/ipl': {
      id: '/agendar/ipl'
      path: '/agendar/ipl'
      fullPath: '/agendar/ipl'
      preLoaderRoute: typeof AgendarIplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/horario': {
      id: '/agendar/horario'
      path: '/agendar/horario'
      fullPath: '/agendar/horario'
      preLoaderRoute: typeof AgendarHorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/data': {
      id: '/agendar/data'
      path: '/agendar/data'
      fullPath: '/agendar/data'
      preLoaderRoute: typeof AgendarDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/advogado': {
      id: '/agendar/advogado'
      path: '/agendar/advogado'
      fullPath: '/agendar/advogado'
      preLoaderRoute: typeof AgendarAdvogadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/convite': {
      id: '/admin/convite'
      path: '/convite'
      fullPath: '/admin/convite'
      preLoaderRoute: typeof AdminConviteRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConviteRoute: typeof AdminConviteRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConviteRoute: AdminConviteRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultarRoute: ConsultarRoute,
  GestaoRoute: GestaoRoute,
  AgendarAdvogadoRoute: AgendarAdvogadoRoute,
  AgendarDataRoute: AgendarDataRoute,
  AgendarHorarioRoute: AgendarHorarioRoute,
  AgendarIplRoute: AgendarIplRoute,
  AgendarRegrasRoute: AgendarRegrasRoute,
  AgendarRevisaoRoute: AgendarRevisaoRoute,
  AgendarSucessoRoute: AgendarSucessoRoute,
  AgendarUnidadeRoute: AgendarUnidadeRoute,
  DocumentoAdvogadoRoute: DocumentoAdvogadoRoute,
  DocumentoIplRoute: DocumentoIplRoute,
  DocumentoRevisaoRoute: DocumentoRevisaoRoute,
  DocumentoSucessoRoute: DocumentoSucessoRoute,
  DocumentoUnidadeRoute: DocumentoUnidadeRoute,
  DocumentoUploadRoute: DocumentoUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

